Add pending OSS project
gradle/gradle-enterprise-oss-projects pull request #4
Opened 2022-05-02 13:17 UTC by jprinet

Signed-off-by: Jerome Prinet <jprinet@gradle.com>

2022-05-03 11:31 UTC, jprinet commented
Kotlin uses dependency verification meaning a fork is required to run the experiments with the scripts as it introduces an extra dependency on GE Gradle plugin 3.10.

2022-05-09 14:02 UTC, etiennestuder requested changes

2022-05-09 14:02 UTC, etiennestuder commented on .github/workflows/run-experiments-jhipster.yml
> +          args: ${{ env.ARGS }}
can be ommitted.

2022-05-09 14:02 UTC, etiennestuder commented on .github/workflows/run-experiments-detekt.yml
> +          args: ${{ env.ARGS }}
can be ommitted

2022-05-09 14:02 UTC, etiennestuder commented on .github/workflows/run-experiments-kotlin.yml
> +      - name: Display toolchain
Is this step needed?

2022-05-09 14:12 UTC, jprinet commented on .github/workflows/run-experiments-jhipster.yml
> +          args: ${{ env.ARGS }}
good catch

2022-05-09 14:15 UTC, jprinet commented on .github/workflows/run-experiments-kotlin.yml
> +      - name: Display toolchain
Not strictly, but if _JDK_ 6 or 7 get patched, which happened lately, the _JAVA_HOME_ path (ie. `/opt/hostedtoolcache/jdk/7.0.342`) is updated and displaying the toolchain is a great way to catch that.

2022-05-09 17:35 UTC, merged